services:
  - type: web
    name: job-application-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://swayamvernekar5_db_user:Byp33HpwuzxOPh76@gprcluster0.u2slucx.mongodb.net/?appName=GPRCluster0

      - key: PORT
        value: 3000

      - key: MAX_FILE_SIZE
        value: 20971520

      - key: ALLOWED_FILE_TYPES
        value: .pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document